version: '3'
services:
  express:
      build: "./backend"
      image: "dockerbackend:latest"
      container_name: express
      ports:
      - "5000:5000"
      # networks:
      # - backend
  next:
      build: "./frontend"
      image: "dockerfrontend:latest"
      container_name: next
      ports:
      - "3000:3000"
      # networks:
      # - backend
  nginx:
      container_name: nginx
      image: "nginx:latest"
      ports:
       - "80:80"
      # networks:
      #  - backend
 
# networks: # 가장 기본적인 bridge 네트워크
#   backend:
#     driver: bridge