version: '3'
services:
  flask:
      container_name: flask
      image: "flask:test"
      ports:
       - "5000:5000"
      networks:
      - backend
  nginx:
      container_name: nginx
      image: "nginx:test"
      ports:
       - "80:80"
      networks:
       - backend
 
networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge